runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT akki_django_app.wsgi:application

handlers:
- url: /static
 static_dir: static/

- url: /.*
 script: auto

runtime_config:
 python_version: 3
