name: Django New CI 5th Jan 2024

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #         branches:
  #             - main

  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check files using the black formatter
      uses: rickstaa/action-black@v1
      id: action_black
      with:
        black_args: "."

    - name: Check if files were formatted
      id: check_formatted
      run: |
        if [[ $(git diff --name-only) ]]; then
          echo "::set-output name=is_formatted::true"
        else
          echo "::set-output name=is_formatted::false"
        fi

    - name: Create Pull Request
      if: steps.check_formatted.outputs.is_formatted == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ":art: Format Python code with psf/black"
        title: "Format Python code with psf/black"
        body: |
          There appear to be some python formatting errors in ${{ github.sha }}. This pull request
          uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
        base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch

    - name: Format HTML, CSS, and JS with Prettier
      uses: actionsx/prettier@v2
      with:
        args: --write "akki_django_app/akki_django_app/templates/**/*.{html,css,js}"

    - name: Check if files were formatted (Prettier)
      id: check_prettier
      run: |
        if [[ $(git diff --name-only) ]]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi

    - name: Create Pull Request (Prettier)
      if: steps.check_prettier.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Apply Prettier formatting"
        title: "Apply Prettier formatting"
        body: "This PR applies Prettier formatting to HTML, CSS, and JS files."
        base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch

    - name: Migrations
      run: |
        python akki_django_app/manage.py makemigrations
        python akki_django_app/manage.py migrate

    - name: Auto Commit Action
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Testing Akki Commit Message
        file_pattern: '!*.github/workflows/ci_django.yml'
