name: Deploy to Google App Engine

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Print Current Path
      run: pwd

    - name: List Files in Directory
      run: ls akki_django_app

    - name : check_permission
      run: ls -l akki_django_app

    - name: List Directory Structure
      run: tree


    # - name: Run tests
    #   run: python manage.py test

    - name: Setup GCP Authentication
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_2 }}
        # workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        # service_account: '${{ secrets.SERVICE_ACCOUNT }}'

    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        project_id: nomadic-vehicle-404406
        version: v1
        deliverables: app.yaml
        working_directory: akki_django_app
