name: CD Pipeline to Deploy the app to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        # akki
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 400 private_key.pem
        # mkdir -p ~/.ssh
        # touch ~/.ssh/known_hosts
        # ssh-keyscan -H ${{ secrets.EC2_IP_ADDRESS }} >> ~/.ssh/known_hosts
        # ssh-keygen -R hostname
        # ssh -i private_key.pem ec2-user@${{ secrets.EC2_IP_ADDRESS }} <<EOF
        # chmod 400 ~/.ssh/known_hosts
        # ssh -i private_key.pem -T ec2-user@${{ secrets.EC2_IP_ADDRESS }} <<EOF
        ssh -i private_key.pem ubuntu@${{ secrets.EC2_IP_ADDRESS }} <<EOF
        echo "HOSTNAME"
        hostname -I
        EOF
