name: CD Pipeline to Deploy the app to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        # akki
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 400 private_key.pem
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.EC2_IP_ADDRESS }} >> ~/.ssh/known_hosts
        # ssh-keygen -R hostname
        # ssh -i private_key.pem ec2-user@${{ secrets.EC2_IP_ADDRESS }} <<EOF
        # chmod 400 ~/.ssh/known_hosts
        # ssh -i private_key.pem -T ec2-user@${{ secrets.EC2_IP_ADDRESS }} <<EOF
        ssh -i private_key.pem -T ubuntu@${{ secrets.EC2_IP_ADDRESS }} <<EOF
        echo "HOSTNAME"
        hostname -I
        echo "Checking for Update" 
        sudo apt-get update
        sudo apt-get upgrade -y
        echo "Installing pip"
        sudo apt install python3-pip -y
        echo "Cloning Repo"
        git clone https://github.com/Akshit-Trivedi-Inferenz/Akki-Django-2.git
        cd Akki-Django-2/
        git checkout main
        git pull origin main
        pip install -r requirements.txt
        cd akki_django_app/
        python3 manage.py makemigrations
        python3 manage.py migrate
        echo "Running the Server"
        python3 manage.py runserver 0.0.0.0:8000
        EOF
