name: Create a Comment on new issues

on:
  issues:
    types: [opened]

permissions: write-all

jobs:
  comment-with-community-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump GitHub context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for Highlighting the Issue, Our Team is Working on it. :sparkles:
          #   This is a multi-line test comment
          #   - With GitHub **Markdown** :sparkles:
          #   - Created by [create-or-update-comment][1]
  
          #   [1]: https://github.com/peter-evans/create-or-update-comment
          # reactions: '+1'
          reactions: '+1, -1, laugh, confused, heart, hooray, rocket, eyes'

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment but from the API Call not action :sparkles:
            '


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
